class ExitException(Exception):
    """Exception raised then exit command called"""
